basic_board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("notices/", include("noticeapp.urls")),
]

core/urls.py
from django.urls import path
from core.views import home, assignment, service


app_name = "core"


urlpatterns = [
    path("", home, name="home"),
    path("assignment/", assignment, name="assignment"),
    path("service/", service, name="service")    
]

noticeapp/urls.py
from django.urls import path
from noticeapp.views import NoticeCreateView, NoticeListView, NoticeDetailView, NoticeUpdateView, NoticeDeleteView



app_name = "noticeapp"



urlpatterns = [
    path("create/", NoticeCreateView.as_view(), name="create"),
    path("list/", NoticeListView.as_view(), name="list"),
    path("detail/<int:pk>", NoticeDetailView.as_view(), name="detail"),
    path("update/<int:pk>", NoticeUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", NoticeDeleteView.as_view(), name="delete"),
]

core/models.py
from django.db import models

# Create your models here.

freeapp/models.py
from django.db import models

# Create your models here.

gallaryapp/models.py
from django.db import models

# Create your models here.

noticeapp/models.py
from django.db import models
from django.db.models.fields import CharField

class Notice(models.Model) :
    
    TYPE_CHOICE = (
        ("A.공지사항", "A.공지사항"),
        ("B.새소식", "B.새소식"),
        ("C.기타", "C.기타"),
    )
    title = models.CharField(max_length=200, null=False)
    type = models.CharField(max_length=20, choices=TYPE_CHOICE, null=True, blank=True)
    content = models.TextField(null=False)
    create_at = models.DateField(auto_now_add=True)
    
    def __str__(self) :
        return self.title
    
    

noticeapp/forms.py
from django.forms import ModelForm
from noticeapp.models import Notice


class NoticeCreationForm(ModelForm) :
    class Meta :
        model = Notice
        fields = ['title','content']

core/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home(request) :
    return render(request, "core/home.html")

def assignment(request) :
    return render(request, "core/assignment.html")

def service(request) :
    return render(request, "core/service.html")

freeapp/views.py
from django.shortcuts import render

# Create your views here.

gallaryapp/views.py
from django.shortcuts import render

# Create your views here.

noticeapp/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, UpdateView
from noticeapp.models import Notice
from noticeapp.forms import NoticeCreationForm
from django.urls import reverse_lazy



class NoticeCreateView(CreateView) :
    model = Notice
    form_class = NoticeCreationForm
    template_name = "noticeapp/create.html"
    success_url = reverse_lazy('noticeapp:list') #기억

class NoticeListView(ListView) :
    model = Notice
    context_object_name = "notice_list"
    template_name = "noticeapp/list.html"
    paginate_by = 20
    
    def get_queryset(self) :
        search = self.request.GET.get("search")

        if search == None or search == "전체":
            model = Notice.objects.all()
            return model
        else :
            model = Notice.objects.filter(type=search)
            return model
    
    def get_context_data(self, *args, **kwargs) :
        context = super(NoticeListView, self).get_context_data(**kwargs)
        
        notice_list = Notice.objects.all().order_by("-type")
        type_list = []
        
        
        for notice in notice_list :
            type_list.append(notice.type)
            
        type_list = list(set(type_list))
        
        context['type_list'] = type_list
        
        return context
    
    def get(self, *args, **kwargs) :
        
        
        return super(NoticeListView, self).get(args, kwargs)

class NoticeDetailView(DetailView) :
    model = Notice
    context_object_name = "target_notice"
    template_name = "noticeapp/detail.html"
    
    
class NoticeUpdateView(UpdateView) :
    model = Notice
    context_object_name = "target_notice"
    form_class = NoticeCreationForm
    template_name = "noticeapp/update.html"
    success_url = reverse_lazy('noticeapp:list')
    
class NoticeDeleteView(DeleteView) :
    model = Notice
    context_object_name = "target_notice"
    template_name = "noticeapp/delete.html"
    success_url = reverse_lazy('noticeapp:list')
    
    
    
    
    
    

core/templates/core/assignment.html
{% extends 'base.html' %}



{% block content %}
<h2>Hello assignment</h2>
    
{% endblock content %}
    

core/templates/core/home.html
{% extends 'base.html' %}



{% block content %}
<h2>Hello Home</h2>
    
{% endblock content %}
    

core/templates/core/service.html
{% extends 'base.html' %}



{% block content %}
<h2>Hello service</h2>
    
{% endblock content %}
    

noticeapp/templates/noticeapp/create.html
{% extends 'base.html' %}

{% load bootstrap4 %}


{% block content %}

<div>
    <form action="{% url 'noticeapp:create' %}" method="POST">
        {% csrf_token %}
        
        {% bootstrap_form form %}
        <input type="submit" value="글 등록" />
    </form>

</div>
    
{% endblock content %}
    

noticeapp/templates/noticeapp/delete.html
{% extends 'base.html' %}



{% block content %}

    <form action="{% url 'noticeapp:delete' pk=target_notice.pk%}" method="POST">
        {% csrf_token %}
        <input type="submit" value="삭제하시겠습니까?">
    </form>

    
{% endblock content %}
    

noticeapp/templates/noticeapp/detail.html
{% extends 'base.html' %}



{% block content %}

<div>
    <h1>{{target_notice.title}}  </h1>
    <h6>{{target_notice.create_at}}</h6>
    <hr>
    <h4>{{target_notice.content}}</h4>
  
</div>

<div>
    <a href="{% url 'noticeapp:update' pk=target_notice.pk %}">Update</a>
    <a href="{% url 'noticeapp:delete' pk=target_notice.pk %}">Delete</a>
</div>

    
{% endblock content %}
    

noticeapp/templates/noticeapp/list.html
{% extends 'base.html' %}


{% block content %}
<div class="boardbox">
    <div>
        <form action="{%  url 'noticeapp:list' %}" method="get">
            <input type="hidden" name="search" value="전체">
            <button>전체</button>
        </form>
        {% for type in type_list %}
        <form action="{%  url 'noticeapp:list' %}" method="get">
            <input type="hidden" name="search" value="{{type}}">
            <button>{{type}}</button>
        </form>
            
        {% endfor %}
            
    </div>
    <div class="col-10">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">No</th>
                <th scope="col">Title</th>
                <th scope="col">User</th>
                <th scope="col">Date</th>
            </tr>
            </thead>
            <tbody>
                {% for notice in notice_list %}
            <tr>
                <th scope="row">{{notice.pk}}</th>
                <td>{{notice.type}}</td>
                <td><a href="{% url 'noticeapp:detail' pk=notice.pk %}">
                    {{notice.title}}
                </a></td>
                <td>Master</td>
                <td>{{notice.create_at}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

</div>








<hr>

<div>
    <a href="{% url 'noticeapp:create' %}">글 작성하기</a>
</div>
    
{% endblock content %}
    

noticeapp/templates/noticeapp/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}


{% block content %}

<div>
    <form action="{% url 'noticeapp:update' pk=target_notice.pk %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="글 수정" />
    </form>

</div>
    
{% endblock content %}
    

templates/base.html
<!DOCTYPE html>
<html lang="ko">
  {% include 'head.html' %}
  <body>
    {% include 'header.html' %}

    <div class="main">{% block content %} {% endblock content %}</div>

    {% include 'footer.html' %}
  </body>
</html>

templates/footer.html
<div class="footer">
  <div>
    <h2>4leaf_borad</h2>
  </div>

  <div>
    <span><a href="{% url 'core:assignment' %}"> 이용약관</a></span>
    <span>| </span>
    <span><a href="{% url 'core:service' %}"> 서비스소개</a></span>
  </div>
</div>

templates/head.html
{% load static %}

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>4leaf|borad</title>
  <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}" />

  <!-- google fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link
    href="https://fonts.googleapis.com/css2?family=Otomanopee+One&display=swap"
    rel="stylesheet"
  />
  <!-- bootstrap -->
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
    crossorigin="anonymous"
  />
</head>

templates/header.html
<div class="header">
  <div>
    <h1>
      <a href="{% url 'core:home' %}"> 4leaf_borad </a>
    </h1>
  </div>

  <div>
    <span><a href="{% url 'noticeapp:list' %}"> Notice </a> </span>
    <span>|</span>
    <span>Gallary</span>
    <span>|</span>
    <span>Free</span>
  </div>
</div>